version: "3"
services:

  nginx:
    image: spengler.grph.xyz/release/nginx-proxy:2000
    ports:
      - 80:80
      - 443:443
    links:
      - pivot
      - central
    # volumes:
    #   - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - ./etc/nginx/graphistry.conf:/etc/nginx/conf.d/graphistry.conf
    #   - ./etc/nginx/ssl.self-provided.conf:/etc/nginx/graphistry/ssl.conf
    #   - ./etc/ssl:/etc/ssl

  central:
    image: spengler.grph.xyz/release/graphistry-central:2000
    depends_on:
      - mongo
    links:
      - mongo
    env_file:
      - .env

  viz:
    image: spengler.grph.xyz/release/graphistry-viz:2000
    links:
      - mongo
    env_file:
      - .env

  pivot:
    image: spengler.grph.xyz/release/graphistry-pivot:2000
    env_file:
      - .env
    links:
      - central

  mongo:
    image: spengler.grph.xyz/release/mongo:3.2.20
    env_file:
      - .env
