version: "3"
services:

  nginx:
    image: spengler.grph.xyz/bundle/nginx-proxy:2001
    container_name: graphistry
    ports:
      - 80:80
      - 443:443
    links:
      - viz
      - pivot
      - central
    # volumes:
    #   - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - ./etc/nginx/graphistry.conf:/etc/nginx/conf.d/graphistry.conf
    #   - ./etc/nginx/ssl.self-provided.conf:/etc/nginx/graphistry/ssl.conf
    #   - ./etc/ssl:/etc/ssl

  central:
    image: spengler.grph.xyz/bundle/graphistry-central:2001
    depends_on:
      - mongo
    links:
      - mongo
    env_file:
      - .env

  viz:
    image: spengler.grph.xyz/bundle/graphistry-viz:2001
    depends_on:
      - mongo
    links:
      - mongo
    env_file:
      - .env
    volumes:
      - ${GRAPHISTRY_VIZ}:${GRAPHISTRY_VIZ_CONTAINER_DIR}

  pivot:
    image: spengler.grph.xyz/bundle/graphistry-pivot:2001
    env_file:
      - .env
    links:
      - central
    volumes:
       - ${GRAPHISTRY_CONFIG}:/opt/graphistry/config
       - ${GRAPHISTRY_INVESTIGATIONS}:${GRAPHISTRY_INVESTIGATIONS_CONTAINER_DIR}

  mongo:
    image: spengler.grph.xyz/bundle/mongo:3.2.20
    env_file:
      - .env
